version: '3.7'

services:
  laravel-app:
    build:
      context: '.'
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - laravel-app

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - persistent:/var/lib/mysql
    ports: 
      - "1234:3306"
    command: --default-authentication-plugin=mysql_native_password  
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
    networks:
      backend:
        aliases:
          - db

networks:
  backend:
    name: backend-network

volumes:
    persistent:
